name: "Build | EBD Image"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["uat-**/ebd", "prod-**/ebd"]
    paths:
      [
        "apps/ebd/**",
        "packages/**",
        "package.json",
        ".github/workflows/build-ebd-image.yml",
      ]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "ghcr.io/trn-lab/eth-bridge-daemon"

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_VERSION: ${{ steps.build-publish-step.outputs.version }}
      ENV_NAME: ${{ steps.build-publish-step.outputs.env_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: ghcr.io login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ðŸ›  & Publish ðŸ³
        id: build-publish-step
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)

          if [[ "$GITHUB_REF" == *"prod"* ]]; then ENV_NAME="rootnet-au-prod"; fi
          if [[ "$GITHUB_REF" == *"uat"* ]]; then ENV_NAME="rootnet-au-dev"; fi

          echo "github ref": $GITHUB_REF
          echo "commit hash: $COMMIT_HASH"
          echo "branch environment: $ENV_NAME"

          # Set output
          echo "version=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "env_name=${ENV_NAME}" >> $GITHUB_OUTPUT

          # skip docker build when image with $COMMIT_HASH tag already exists
          if [ -n "$(docker images -q "$IMAGE_NAME":"$COMMIT_HASH")" ]; then
            echo "docker build skipped because image already exists"
            exit 0
          fi

          docker build -t "$IMAGE_NAME":"$COMMIT_HASH" -f ./Dockerfile.ebd .
          docker push "$IMAGE_NAME":"$COMMIT_HASH"

          # branch is dev
          if [ -n "$ENV_NAME" ]; then
            docker tag "$IMAGE_NAME":"$COMMIT_HASH" "$IMAGE_NAME":"$ENV_NAME"
            docker push "$IMAGE_NAME":"$ENV_NAME"
          fi

          # branch is default branch
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            docker tag "$IMAGE_NAME":"$COMMIT_HASH" "$IMAGE_NAME":latest
            docker push "$IMAGE_NAME":latest
          fi

          # clean up images
          docker image prune --filter label=stage=build -f
